// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrjqdsUYlRp8_WhifeAzOKAtVmH28XH48',
    appId: '1:447330149286:web:60f83d912c9994e7932567',
    messagingSenderId: '447330149286',
    projectId: 'kuntuckt-a1835',
    authDomain: 'kuntuckt-a1835.firebaseapp.com',
    storageBucket: 'kuntuckt-a1835.appspot.com',
    measurementId: 'G-6J5130XZRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJtZmL23-GWI5TYPhv_Umb6mvIu4omOF0',
    appId: '1:447330149286:android:8288c746d810c13d932567',
    messagingSenderId: '447330149286',
    projectId: 'kuntuckt-a1835',
    storageBucket: 'kuntuckt-a1835.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTWY1_z0jSkve63aI_RzGjm3GestjPF34',
    appId: '1:447330149286:ios:041f2cfeb5f1b45a932567',
    messagingSenderId: '447330149286',
    projectId: 'kuntuckt-a1835',
    storageBucket: 'kuntuckt-a1835.appspot.com',
    iosBundleId: 'com.example.kuntuckt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTWY1_z0jSkve63aI_RzGjm3GestjPF34',
    appId: '1:447330149286:ios:6014b00d118c667e932567',
    messagingSenderId: '447330149286',
    projectId: 'kuntuckt-a1835',
    storageBucket: 'kuntuckt-a1835.appspot.com',
    iosBundleId: 'com.example.kuntuckt.RunnerTests',
  );
}
